### ISSUE TITLE
Make "TimeStyleBuilder" public or expose time features from "DateStyleBuilder"

### ISSUE THREAD

**Issue by negora** [jferard/fastods#144]
Other style builders are public but `TimeStyleBuilder` is package-private. I don't know whether making it public may have some serious consequences that I'm not aware of...

Related to this, I wonder if it would be better that `DateStyleBuilder` absorbed the functionality of `TimeStyleBuilder`, because there may be situations in which one wants to combine a date with a time in the same cell (i.e. `2019-04-01 11:24:00`).

**Comment by jferard** [comment]
I thinnk I didn't make it public since there is currently only one time style available (`HH:MM:SS`) and it's "buried" in the default data styles. I will make it public, but I need to make it more flexible (like `DateStyleBuilder` and `DateStyleFormat`).

I won't merge both, since `time` and `date` are different beasts in ODF (see http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#__RefHeading__1417680_253892949) and have different data styles: http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#element-number_date-style and http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#element-number_time-style).

**Comment by negora** [comment]
Perfect! Thank you... And apologizes for "flooding" you with so many tickets.

**Comment by jferard** [comment]
I was not used to have so much activity on FastODS, but it's ok!

**Comment by jferard** [comment]
@negora See new "bricks" in https://github.com/jferard/fastods/blob/master/fastods/src/main/java/com/github/jferard/fastods/datastyle/DateStyleFormat.java to build date/time style formats, and the example in https://github.com/jferard/fastods/blob/master/fastods/src/test/java/com/github/jferard/fastods/it/DataStyleExampleIT.java (5th et 6th rows).

**Comment by negora** [comment]
@jferard Great! I've just tried it and it has worked fine :+1: .

Thank you also for including long options for the time fields ;) .
