### ISSUE TITLE
Excel complains when loading .ods document created by FastODS

### ISSUE THREAD

**Issue by GregorySokoloff** [jferard/fastods#167]
Loading an .ods document into Excel (V 1909 Build 12026.20264), a dialog pops up that says, "We found a problem with some content in 'minimaldoc.ods'. Do you want us to try to recover as much as we can?" Click yes and all seems fine. Likely to be a problem with all documents created by FastODS.

Here is some code to create the minimal document:

```
OdsFactory odsFactory = OdsFactory.create(Logger.getLogger("hello-world"), Locale.US);
AnonymousOdsFileWriter writer = odsFactory.createWriter();
OdsDocument document = writer.document();
Table table = document.addTable("Worksheet1");
File file = new File(filesDir, "junk.ods");
writer.saveAs(file);
```

**Comment by ablundgren** [comment]
I am seeing this issue as well.

**Comment by jferard** [comment]
Hi @ablundgren. This issue was first raised [here](https://github.com/jferard/fastods/issues/142#issuecomment-538676369). My reply was:

> Feel free to post Excel related issues. **I won't investigate these issues because I do not have Excel**, but I'll use the tag "help wanted" and we'll see if someone finds why Excel whines about FastODS files.

Unfortunately, if you don't have any clue, you'll have to wait and hope someone can fix it! BTW, I'm curious about what bothers Excel and hope someone will provide some hints (a log, a modification of the XML that makes the file readable, ...).

**Comment by ueen** [comment]
Should be resolved with this https://github.com/jferard/fastods/issues/216

**Comment by jferard** [comment]
I'm closing this issue, see post above.
